export interface KpiVedette {
  code: string;
  label: string;
  value: number;
  unit: string;
  format: "pct" | "num" | "decimal";
  delta: number;
  health: "green" | "amber" | "red";
  thresholdGreen: string;
  thresholdAmber: string;
  thresholdRed: string;
  source: string;
  freshness: string; // "il y a 12 min"
  sparkline: number[];
}

export const KPI_AG: KpiVedette[] = [
  {
    code: "EXE-01",
    label: "Santé du portefeuille",
    value: 42,
    unit: "%",
    format: "pct",
    delta: -8,
    health: "red",
    thresholdGreen: "≥ 80 %",
    thresholdAmber: "60–79 %",
    thresholdRed: "< 60 %",
    source: "PMS",
    freshness: "il y a 14 min",
    sparkline: [58, 55, 52, 50, 48, 45, 42],
  },
  {
    code: "EXE-04",
    label: "Avancement Hoshin global",
    value: 67,
    unit: "%",
    format: "pct",
    delta: 3,
    health: "amber",
    thresholdGreen: "≥ 70 %",
    thresholdAmber: "50–69 %",
    thresholdRed: "< 50 %",
    source: "Saisie + PMS",
    freshness: "il y a 2 h",
    sparkline: [55, 58, 60, 62, 64, 65, 67],
  },
  {
    code: "EXE-05",
    label: "Absorption bailleurs YTD",
    value: 85,
    unit: "%",
    format: "pct",
    delta: 4,
    health: "green",
    thresholdGreen: "85–105 %",
    thresholdAmber: "70–84 %",
    thresholdRed: "< 70 % ou > 120 %",
    source: "Grant Office + ERP",
    freshness: "il y a 38 min",
    sparkline: [72, 75, 78, 80, 82, 83, 85],
  },
  {
    code: "EXE-06",
    label: "Escalades en attente AG",
    value: 3,
    unit: "",
    format: "num",
    delta: 1,
    health: "red",
    thresholdGreen: "0",
    thresholdAmber: "1–2",
    thresholdRed: "≥ 3",
    source: "Portail",
    freshness: "temps réel",
    sparkline: [1, 2, 1, 2, 3, 2, 3],
  },
];

export const KPI_CABINET: KpiVedette[] = [
  {
    code: "COO-01",
    label: "Délai moyen résolution escalade",
    value: 42,
    unit: "h",
    format: "num",
    delta: -8,
    health: "green",
    thresholdGreen: "≤ 48 h",
    thresholdAmber: "49–96 h",
    thresholdRed: "> 96 h",
    source: "Portail",
    freshness: "temps réel",
    sparkline: [62, 58, 55, 52, 48, 45, 42],
  },
  {
    code: "COO-02",
    label: "Escalades résolues sans AG",
    value: 68,
    unit: "%",
    format: "pct",
    delta: 5,
    health: "amber",
    thresholdGreen: "≥ 70 %",
    thresholdAmber: "50–69 %",
    thresholdRed: "< 50 %",
    source: "Portail",
    freshness: "il y a 3 h",
    sparkline: [55, 58, 60, 62, 65, 66, 68],
  },
  {
    code: "COO-03",
    label: "Indice collaboration inter-entités",
    value: 71,
    unit: "/100",
    format: "num",
    delta: 4,
    health: "amber",
    thresholdGreen: "≥ 75",
    thresholdAmber: "60–74",
    thresholdRed: "< 60",
    source: "Composite",
    freshness: "il y a 1 j",
    sparkline: [60, 62, 65, 67, 68, 70, 71],
  },
  {
    code: "COO-04",
    label: "Conformité reporting bailleurs",
    value: 92,
    unit: "%",
    format: "pct",
    delta: -2,
    health: "amber",
    thresholdGreen: "≥ 95 %",
    thresholdAmber: "85–94 %",
    thresholdRed: "< 85 %",
    source: "Grant Office",
    freshness: "il y a 30 min",
    sparkline: [88, 90, 91, 93, 94, 93, 92],
  },
];

export const KPI_PM: KpiVedette[] = [
  {
    code: "PM-01",
    label: "Avancement vs plan (MADIBA-2)",
    value: 41,
    unit: "%",
    format: "pct",
    delta: -9,
    health: "red",
    thresholdGreen: "≥ 95 %",
    thresholdAmber: "80–94 %",
    thresholdRed: "< 80 %",
    source: "MS Project",
    freshness: "il y a 8 min",
    sparkline: [50, 48, 46, 44, 43, 42, 41],
  },
  {
    code: "PM-02",
    label: "Consommation budgétaire",
    value: 83,
    unit: "%",
    format: "pct",
    delta: 3,
    health: "amber",
    thresholdGreen: "90–105 %",
    thresholdAmber: "80–89 % / 106–115 %",
    thresholdRed: "< 80 % / > 115 %",
    source: "ERP",
    freshness: "il y a 1 h",
    sparkline: [72, 75, 77, 79, 81, 82, 83],
  },
  {
    code: "PM-03",
    label: "Risques Élevés non mitigés",
    value: 2,
    unit: "",
    format: "num",
    delta: -1,
    health: "amber",
    thresholdGreen: "0",
    thresholdAmber: "1–2",
    thresholdRed: "≥ 3",
    source: "Registre risques",
    freshness: "il y a 4 h",
    sparkline: [3, 4, 3, 3, 3, 2, 2],
  },
  {
    code: "PM-06",
    label: "Conformité projet (charte/plan/registre/reporting)",
    value: 3,
    unit: "/4",
    format: "num",
    delta: 1,
    health: "amber",
    thresholdGreen: "4",
    thresholdAmber: "2–3",
    thresholdRed: "0–1",
    source: "PMS",
    freshness: "il y a 1 j",
    sparkline: [2, 2, 2, 3, 3, 3, 3],
  },
];
