export interface Project {
  id: string;
  code: string;
  name: string;
  entityId: string;
  pillarId: string; // Hoshin
  bailleurIds: string[];
  pmName: string;
  pmInitials: string;
  health: "green" | "amber" | "red";
  status: "actif" | "en_pause" | "clos";
  budget: number; // millions FCFA
  budgetConsumed: number;
  spi: number; // Schedule Performance Index
  cpi: number; // Cost Performance Index
  progress: number; // 0-100
  startDate: string;
  endDate: string;
  risksHighCount: number;
}

export const PROJECTS: Project[] = [
  {
    id: "madiba-2",
    code: "MAD-2",
    name: "MADIBA-2 — Industrialisation vaccin polyvalent",
    entityId: "madiba",
    pillarId: "souverainete",
    bailleurIds: ["cepi", "gates", "bmz"],
    pmName: "Ibrahima Faye",
    pmInitials: "IF",
    health: "red",
    status: "actif",
    budget: 14200,
    budgetConsumed: 5600,
    spi: 0.78,
    cpi: 0.83,
    progress: 41,
    startDate: "2025-01-15",
    endDate: "2027-06-30",
    risksHighCount: 4,
  },
  {
    id: "lassa-kit",
    code: "DTX-12",
    name: "Diatropix Lassa Kit — Diagnostic rapide",
    entityId: "diatropix",
    pillarId: "excellence",
    bailleurIds: ["gates", "edctp"],
    pmName: "Mariama Bâ",
    pmInitials: "MB",
    health: "green",
    status: "actif",
    budget: 1800,
    budgetConsumed: 1240,
    spi: 0.97,
    cpi: 0.99,
    progress: 68,
    startDate: "2025-03-01",
    endDate: "2026-09-30",
    risksHighCount: 0,
  },
  {
    id: "fievre-jaune",
    code: "VAX-08",
    name: "Vaccin fièvre jaune — Extension capacité",
    entityId: "vaccinopole",
    pillarId: "industrialisation",
    bailleurIds: ["cepi", "senegal"],
    pmName: "Ousmane Kane",
    pmInitials: "OK",
    health: "amber",
    status: "actif",
    budget: 8900,
    budgetConsumed: 6100,
    spi: 0.91,
    cpi: 0.93,
    progress: 72,
    startDate: "2024-09-10",
    endDate: "2026-12-15",
    risksHighCount: 2,
  },
  {
    id: "rougeole",
    code: "VAX-14",
    name: "Plateforme rougeole-rubéole",
    entityId: "vaccinopole",
    pillarId: "souverainete",
    bailleurIds: ["wb", "senegal"],
    pmName: "Aminata Ndour",
    pmInitials: "AN",
    health: "amber",
    status: "actif",
    budget: 5400,
    budgetConsumed: 2800,
    spi: 0.87,
    cpi: 0.90,
    progress: 52,
    startDate: "2025-02-01",
    endDate: "2027-03-30",
    risksHighCount: 1,
  },
  {
    id: "covid-19-pasteur",
    code: "VAX-22",
    name: "Vaccin COVID-19 Pasteur — Boosters africains",
    entityId: "madiba",
    pillarId: "souverainete",
    bailleurIds: ["cepi", "wellcome"],
    pmName: "Cheikh Diouf",
    pmInitials: "CD",
    health: "amber",
    status: "actif",
    budget: 6700,
    budgetConsumed: 3100,
    spi: 0.89,
    cpi: 0.95,
    progress: 47,
    startDate: "2024-11-15",
    endDate: "2026-11-30",
    risksHighCount: 2,
  },
  {
    id: "dengue",
    code: "DTX-17",
    name: "Diagnostic Dengue serotypes multiplex",
    entityId: "diatropix",
    pillarId: "excellence",
    bailleurIds: ["edctp", "wellcome"],
    pmName: "Bineta Diallo",
    pmInitials: "BD",
    health: "green",
    status: "actif",
    budget: 1200,
    budgetConsumed: 780,
    spi: 0.98,
    cpi: 1.02,
    progress: 64,
    startDate: "2025-04-01",
    endDate: "2026-10-31",
    risksHighCount: 0,
  },
  {
    id: "formation-gmp",
    code: "RH-03",
    name: "Programme formation GMP — 500 techniciens",
    entityId: "industrielle",
    pillarId: "capital-humain",
    bailleurIds: ["bmz", "senegal"],
    pmName: "Tidiane Sarr",
    pmInitials: "TS",
    health: "amber",
    status: "actif",
    budget: 1800,
    budgetConsumed: 920,
    spi: 0.86,
    cpi: 0.94,
    progress: 51,
    startDate: "2025-01-08",
    endDate: "2026-06-30",
    risksHighCount: 1,
  },
  {
    id: "audit-qms",
    code: "QM-09",
    name: "Refonte QMS — Conformité ISO 13485",
    entityId: "qualite",
    pillarId: "industrialisation",
    bailleurIds: ["gates"],
    pmName: "Khadija Sarr",
    pmInitials: "KS",
    health: "amber",
    status: "actif",
    budget: 950,
    budgetConsumed: 620,
    spi: 0.88,
    cpi: 0.91,
    progress: 65,
    startDate: "2025-03-15",
    endDate: "2026-08-31",
    risksHighCount: 1,
  },
  {
    id: "vih",
    code: "RES-21",
    name: "Recherche VIH — Cohorte panafricaine",
    entityId: "recherche",
    pillarId: "excellence",
    bailleurIds: ["edctp", "usaid", "wellcome"],
    pmName: "Awa Ndiaye",
    pmInitials: "AN",
    health: "green",
    status: "actif",
    budget: 4200,
    budgetConsumed: 2800,
    spi: 0.96,
    cpi: 0.98,
    progress: 67,
    startDate: "2024-07-01",
    endDate: "2027-06-30",
    risksHighCount: 0,
  },
  {
    id: "rougeole-vacc",
    code: "RES-25",
    name: "Étude immunogénicité vaccin combiné",
    entityId: "recherche",
    pillarId: "excellence",
    bailleurIds: ["edctp"],
    pmName: "Mouhamadou Sy",
    pmInitials: "MS",
    health: "green",
    status: "actif",
    budget: 2100,
    budgetConsumed: 1340,
    spi: 0.95,
    cpi: 0.97,
    progress: 64,
    startDate: "2024-10-15",
    endDate: "2026-07-31",
    risksHighCount: 0,
  },
  {
    id: "biosecurite",
    code: "MED-04",
    name: "Plan biosécurité Vaccinopôle BSL-3",
    entityId: "medicale",
    pillarId: "industrialisation",
    bailleurIds: ["senegal", "wb"],
    pmName: "Boubacar Camara",
    pmInitials: "BC",
    health: "green",
    status: "actif",
    budget: 1600,
    budgetConsumed: 1100,
    spi: 0.94,
    cpi: 0.96,
    progress: 69,
    startDate: "2025-02-15",
    endDate: "2026-05-31",
    risksHighCount: 0,
  },
  {
    id: "go-bailleurs",
    code: "GO-07",
    name: "Refonte processus reporting bailleurs",
    entityId: "grant-office",
    pillarId: "impact-societal",
    bailleurIds: ["senegal"],
    pmName: "Cheikh Anta Mbaye",
    pmInitials: "CM",
    health: "green",
    status: "actif",
    budget: 320,
    budgetConsumed: 210,
    spi: 0.99,
    cpi: 1.01,
    progress: 66,
    startDate: "2025-04-01",
    endDate: "2026-03-31",
    risksHighCount: 0,
  },
];

export function projectsByEntity(entityId: string): Project[] {
  return PROJECTS.filter((p) => p.entityId === entityId);
}

export function healthCounts() {
  const total = PROJECTS.length;
  const green = PROJECTS.filter((p) => p.health === "green").length;
  const amber = PROJECTS.filter((p) => p.health === "amber").length;
  const red = PROJECTS.filter((p) => p.health === "red").length;
  return { total, green, amber, red };
}
